### ISSUE TITLE
Create Docker composer.yml files for CrawlerX platform

### ISSUE THREAD

**Issue by poornimarangoda** [leopardslab/CrawlerX#23]
**Is your feature request related to a problem? Please describe.**
$subject. We need to create relevant composer.yml for the platform.

**Describe the solution you'd like**
Type/Improvement

**Comment by sajithaliyanage** [comment]
PR was added as GSoC 2020 task by Poornima Rangoda

**Comment by nimsarapieris** [comment]
I would like to work on this issue.

**Comment by nimsarapieris** [comment]
@sajithaliyanage @poornimarangoda please review the PR https://github.com/leopardslab/CrawlerX/pull/55 which resolves this issue.
