### ISSUE TITLE
Feature: Improve the JSON viewer inside the Job data

### ISSUE THREAD

**Issue by sajithaliyanage** [leopardslab/CrawlerX#39]
We can improve the JSON viewer by adding the followings,

- Add a syntax highlighter 
- Add `Copy to Clipboard` button
- Add some readability improvements

**Comment by ffalpha** [comment]
I like to work on this issue. @sajithaliyanage @poornimarangoda  can you guys provide a db dump ? Cause there is problem in my rabbimq connection .So scrapy server wont collect any data.

**Comment by ffalpha** [comment]
Never mind. I was able to fix it. Will add a PR soon regarding to this issue
